-- Create kitting table and extend build_bom for kitting flag

BEGIN;

-- 1) Kitting table: items chosen as "Kit" on BOM go here
CREATE TABLE IF NOT EXISTS public.kitting (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  requester text NOT NULL,
  project_id text NOT NULL,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  material text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','kitted')),
  workflow text NOT NULL DEFAULT 'kit' CHECK (workflow = 'kit'),
  kitting_bin text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Optional FK to kitting_bins table (safe if table exists)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'kitting_bins'
  ) THEN
    -- Only add the FK if it doesn't already exist (since ALTER TABLE ... ADD CONSTRAINT IF NOT EXISTS is not supported)
    IF NOT EXISTS (
      SELECT 1
      FROM pg_constraint
      WHERE conname = 'kitting_kitting_bin_fkey'
        AND conrelid = 'public.kitting'::regclass
    ) THEN
      ALTER TABLE public.kitting
        ADD CONSTRAINT kitting_kitting_bin_fkey
        FOREIGN KEY (kitting_bin) REFERENCES public.kitting_bins(bin_id)
        ON UPDATE CASCADE ON DELETE SET NULL;
    END IF;
  END IF;
END $$ LANGUAGE plpgsql;

-- Helpful indexes
CREATE INDEX IF NOT EXISTS kitting_status_idx ON public.kitting(status);
CREATE INDEX IF NOT EXISTS kitting_project_idx ON public.kitting(project_id);

-- 2) Extend build_bom snapshot with a "added_to_kitting" flag
ALTER TABLE public.build_bom
  ADD COLUMN IF NOT EXISTS added_to_kitting boolean DEFAULT false;

-- 3) Updated_at trigger helper for kitting table
CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger AS $func$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END
$func$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS kitting_set_updated_at ON public.kitting;
CREATE TRIGGER kitting_set_updated_at
BEFORE UPDATE ON public.kitting
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

COMMIT;
